version: '3.2'
services:
  postgres:
    build:
      context: ./postgres
    image: enzomb/postgres_db:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
    driver: "bridge"